# Generated by Django 3.2.15 on 2022-09-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinavideo',
            name='video',
            field=models.URLField(default=''),
        ),
    ]
